### ISSUE TITLE
Password-Protected Documentation

### ISSUE THREAD

**Issue by broco347** [linkfluence/radarly-py#3]
Is there a reason that the documentation is password protected? I am interested in trying this package out, but I am unable to access the documentation.

**Comment by luhhujbb** [comment]
Hello @broco347, this package is a client for Radarly API Saas product. Documentation access is granted when you buy Radarly subscription.

**Comment by broco347** [comment]
Hi Jean-Baptiste,

Thanks for your response. The organization I work for does have a a Rafaela
subscription. How would I go about accessing the documentation.

Best,
Brooke

**Comment by luhhujbb** [comment]
Your organization should ask credentials to access documentation to your Linkfluence account manager.

Regards
